### ISSUE TITLE
Couldn't install from url

### ISSUE THREAD

**Issue by nicolasnetz** [rekuberate-io/sleepcycles#44]
Hi!

I'm using helm and I'm trying to manage the development pods through this tool, but I wasn't able to install the package on my workload:

I got:

`Error: UPGRADE FAILED: unable to recognize "": no matches for kind "SleepCycle" in version "core.rekuberate.io/v1alpha1"`

My values are:
```
{{- if .Values.sleepcycles.enabled }}
apiVersion: core.rekuberate.io/v1alpha1
kind: SleepCycle
metadata:
  name: sleepcycle-{{ .Values.sleepcycles.app }}
  # namespace: {{ .Release.Namespace }}
spec:
  enabled: true
  shutdown: "{{ .Values.sleepcycles.shutdown }}"
  shutdownTimeZone: "{{ .Values.sleepcycles.shutdownTimeZone }}"
  wakeup: "{{ .Values.sleepcycles.wakeup }}"
  wakeupTimeZone: "{{ .Values.sleepcycles.wakeupTimeZone }}"
{{- end }}
```

```
sleepcycles:
  enabled: true
  app: app-1
  shutdown: "15 12 * * *"
  shutdownTimeZone: "America/Santiago"
  wakeup: "30 12 * * *"
  wakeupTimeZone: "America/Santiago"
```
